"""Init

Revision ID: 1d30e87810fa
Revises: 
Create Date: 2026-05-20 21:43:19.371391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d30e87810fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_calibration',
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dimension')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'INFERENCE', 'ANALYZING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('npz_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=False)
    op.create_table('neural_scores',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('visual_score', sa.Float(), nullable=True),
    sa.Column('auditory_score', sa.Float(), nullable=True),
    sa.Column('emotional_score', sa.Float(), nullable=True),
    sa.Column('attention_score', sa.Float(), nullable=True),
    sa.Column('language_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neural_scores')
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.drop_table('videos')
    op.drop_table('baseline_calibration')
    # ### end Alembic commands ###
